name: Build Tweak

on:
  push:
    branches:
      - main  # 或者 master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Theos dependencies
      run: |
        brew install ldid dpkg

    - name: Clone Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Download SDK (iOS 16.5)
      run: |
        mkdir -p $THEOS/sdks
        curl -L -o $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz
        tar -xf $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz -C $THEOS/sdks

    - name: Build Tweak
      run: |
        make clean package

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: tweak-deb
        path: packages/*.deb
